
package com.sentenial.ws.client.dd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DirectdebitWsService", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir7027886721916410915.tmp/directdebit-ws_1.wsdl")
public class DirectdebitWsService
    extends Service
{

    private final static URL DIRECTDEBITWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIRECTDEBITWSSERVICE_EXCEPTION;
    private final static QName DIRECTDEBITWSSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:directdebit-ws:wsdl", "DirectdebitWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir7027886721916410915.tmp/directdebit-ws_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRECTDEBITWSSERVICE_WSDL_LOCATION = url;
        DIRECTDEBITWSSERVICE_EXCEPTION = e;
    }

    public DirectdebitWsService() {
        super(__getWsdlLocation(), DIRECTDEBITWSSERVICE_QNAME);
    }

    public DirectdebitWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRECTDEBITWSSERVICE_QNAME, features);
    }

    public DirectdebitWsService(URL wsdlLocation) {
        super(wsdlLocation, DIRECTDEBITWSSERVICE_QNAME);
    }

    public DirectdebitWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRECTDEBITWSSERVICE_QNAME, features);
    }

    public DirectdebitWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectdebitWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DirectdebitWs
     */
    @WebEndpoint(name = "DirectdebitWsSoap11")
    public DirectdebitWs getDirectdebitWsSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:directdebit-ws:wsdl", "DirectdebitWsSoap11"), DirectdebitWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectdebitWs
     */
    @WebEndpoint(name = "DirectdebitWsSoap11")
    public DirectdebitWs getDirectdebitWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:directdebit-ws:wsdl", "DirectdebitWsSoap11"), DirectdebitWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRECTDEBITWSSERVICE_EXCEPTION!= null) {
            throw DIRECTDEBITWSSERVICE_EXCEPTION;
        }
        return DIRECTDEBITWSSERVICE_WSDL_LOCATION;
    }

}
