
package com.sentenial.ws.client.dd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectdebitWs", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectdebitWs {


    /**
     * 
     * @param viewDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.ViewDirectDebitResponse
     */
    @WebMethod(operationName = "ViewDirectDebit")
    @WebResult(name = "ViewDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ViewDirectDebitResponse")
    public ViewDirectDebitResponse viewDirectDebit(
        @WebParam(name = "ViewDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ViewDirectDebitRequest")
        ViewDirectDebitRequest viewDirectDebitRequest);

    /**
     * 
     * @param revokeDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.RevokeDirectDebitResponse
     */
    @WebMethod(operationName = "RevokeDirectdebit")
    @WebResult(name = "RevokeDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RevokeDirectDebitResponse")
    public RevokeDirectDebitResponse revokeDirectdebit(
        @WebParam(name = "RevokeDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RevokeDirectDebitRequest")
        RevokeDirectDebitRequest revokeDirectDebitRequest);

    /**
     * 
     * @param cancelDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.CancelDirectDebitResponse
     */
    @WebMethod(operationName = "CancelDirectdebit")
    @WebResult(name = "CancelDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "CancelDirectDebitResponse")
    public CancelDirectDebitResponse cancelDirectdebit(
        @WebParam(name = "CancelDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "CancelDirectDebitRequest")
        CancelDirectDebitRequest cancelDirectDebitRequest);

    /**
     * 
     * @param listDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.ListDirectDebitResponse
     */
    @WebMethod(operationName = "ListDirectdebit")
    @WebResult(name = "ListDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ListDirectDebitResponse")
    public ListDirectDebitResponse listDirectdebit(
        @WebParam(name = "ListDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ListDirectDebitRequest")
        ListDirectDebitRequest listDirectDebitRequest);

    /**
     * 
     * @param activateRevokedDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.ActivateRevokedDirectDebitResponse
     */
    @WebMethod(operationName = "ActivateRevokedDirectDebit")
    @WebResult(name = "ActivateRevokedDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ActivateRevokedDirectDebitResponse")
    public ActivateRevokedDirectDebitResponse activateRevokedDirectDebit(
        @WebParam(name = "ActivateRevokedDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ActivateRevokedDirectDebitRequest")
        ActivateRevokedDirectDebitRequest activateRevokedDirectDebitRequest);

    /**
     * 
     * @param revokeAllDirectDebitsRequest
     * @return
     *     returns com.sentenial.ws.client.dd.RevokeAllDirectDebitsResponse
     */
    @WebMethod(operationName = "RevokeAllDirectDebits")
    @WebResult(name = "RevokeAllDirectDebitsResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RevokeAllDirectDebitsResponse")
    public RevokeAllDirectDebitsResponse revokeAllDirectDebits(
        @WebParam(name = "RevokeAllDirectDebitsRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RevokeAllDirectDebitsRequest")
        RevokeAllDirectDebitsRequest revokeAllDirectDebitsRequest);

    /**
     * 
     * @param listFailingDirectDebitsRequest
     * @return
     *     returns com.sentenial.ws.client.dd.ListFailingDirectDebitsResponse
     */
    @WebMethod(operationName = "ListFailedPayments")
    @WebResult(name = "ListFailingDirectDebitsResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ListFailingDirectDebitsResponse")
    public ListFailingDirectDebitsResponse listFailedPayments(
        @WebParam(name = "ListFailingDirectDebitsRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ListFailingDirectDebitsRequest")
        ListFailingDirectDebitsRequest listFailingDirectDebitsRequest);

    /**
     * 
     * @param representFailedDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.RepresentFailedDirectDebitResponse
     */
    @WebMethod(operationName = "RepresentFailedDirectDebit")
    @WebResult(name = "RepresentFailedDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RepresentFailedDirectDebitResponse")
    public RepresentFailedDirectDebitResponse representFailedDirectDebit(
        @WebParam(name = "RepresentFailedDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "RepresentFailedDirectDebitRequest")
        RepresentFailedDirectDebitRequest representFailedDirectDebitRequest);

    /**
     * 
     * @param addSinglePaymentRequest
     * @return
     *     returns com.sentenial.ws.client.dd.AddSinglePaymentResponse
     */
    @WebMethod(operationName = "AddSinglePayment")
    @WebResult(name = "AddSinglePaymentResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "AddSinglePaymentResponse")
    public AddSinglePaymentResponse addSinglePayment(
        @WebParam(name = "AddSinglePaymentRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "AddSinglePaymentRequest")
        AddSinglePaymentRequest addSinglePaymentRequest);

    /**
     * 
     * @param reverseDirectDebitRequest
     * @return
     *     returns com.sentenial.ws.client.dd.ReverseDirectDebitResponse
     */
    @WebMethod(operationName = "ReverseDirectdebit")
    @WebResult(name = "ReverseDirectDebitResponse", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ReverseDirectDebitResponse")
    public ReverseDirectDebitResponse reverseDirectdebit(
        @WebParam(name = "ReverseDirectDebitRequest", targetNamespace = "urn:com:sentenial:origix:ws:directdebit-ws", partName = "ReverseDirectDebitRequest")
        ReverseDirectDebitRequest reverseDirectDebitRequest);

}
