
package com.sentenial.ws.client.usermgmnt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserManagementWsService", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir7326010635146311850.tmp/usermgmnt-ws_1.wsdl")
public class UserManagementWsService
    extends Service
{

    private final static URL USERMANAGEMENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERMANAGEMENTWSSERVICE_EXCEPTION;
    private final static QName USERMANAGEMENTWSSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:usermgmnt-ws:wsdl", "UserManagementWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir7326010635146311850.tmp/usermgmnt-ws_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERMANAGEMENTWSSERVICE_WSDL_LOCATION = url;
        USERMANAGEMENTWSSERVICE_EXCEPTION = e;
    }

    public UserManagementWsService() {
        super(__getWsdlLocation(), USERMANAGEMENTWSSERVICE_QNAME);
    }

    public UserManagementWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERMANAGEMENTWSSERVICE_QNAME, features);
    }

    public UserManagementWsService(URL wsdlLocation) {
        super(wsdlLocation, USERMANAGEMENTWSSERVICE_QNAME);
    }

    public UserManagementWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERMANAGEMENTWSSERVICE_QNAME, features);
    }

    public UserManagementWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagementWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserManagementWs
     */
    @WebEndpoint(name = "UserManagementWsSoap11")
    public UserManagementWs getUserManagementWsSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:usermgmnt-ws:wsdl", "UserManagementWsSoap11"), UserManagementWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagementWs
     */
    @WebEndpoint(name = "UserManagementWsSoap11")
    public UserManagementWs getUserManagementWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:usermgmnt-ws:wsdl", "UserManagementWsSoap11"), UserManagementWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERMANAGEMENTWSSERVICE_EXCEPTION!= null) {
            throw USERMANAGEMENTWSSERVICE_EXCEPTION;
        }
        return USERMANAGEMENTWSSERVICE_WSDL_LOCATION;
    }

}
