
package com.sentenial.ws.client.usermgmnt;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserManagementWs", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws:wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManagementWs {


    /**
     * 
     * @param returnCode
     * @param usrTtle
     * @param usrSts
     * @param unqId
     * @param usrFrstNm
     * @param usrLng
     * @param usrEmail
     * @param rlCrdnts
     * @param usrLstNm
     * @param cmmnNm
     * @param usrNm
     * @param usrPsswrd
     * @param usrFaxNm
     * @param usrPhnNmbr
     * @param returnDesc
     * @param usrMblNmbr
     */
    @WebMethod(operationName = "AddUser")
    @RequestWrapper(localName = "AddUser", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserType")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserResponseType")
    public void addUser(
        @WebParam(name = "UsrNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrNm,
        @WebParam(name = "UnqId", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> unqId,
        @WebParam(name = "RlCrdnts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<List<RoleCoordinatesType>> rlCrdnts,
        @WebParam(name = "UsrTtle", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<UserTitleType> usrTtle,
        @WebParam(name = "UsrFrstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrFrstNm,
        @WebParam(name = "UsrLstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrLstNm,
        @WebParam(name = "UsrPhnNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrPhnNmbr,
        @WebParam(name = "UsrMblNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrMblNmbr,
        @WebParam(name = "UsrEmail", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrEmail,
        @WebParam(name = "UsrFaxNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrFaxNm,
        @WebParam(name = "CmmnNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> cmmnNm,
        @WebParam(name = "UsrPsswrd", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrPsswrd,
        @WebParam(name = "UsrLng", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<LanguageType> usrLng,
        @WebParam(name = "UsrSts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<StatusType> usrSts,
        @WebParam(name = "returnCode", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnCode,
        @WebParam(name = "returnDesc", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnDesc);

    /**
     * 
     * @param returnCode
     * @param usrTtle
     * @param usrSts
     * @param unqId
     * @param usrFrstNm
     * @param usrLng
     * @param usrEmail
     * @param rlCrdnts
     * @param usrLstNm
     * @param cmmnNm
     * @param usrNm
     * @param usrPsswrd
     * @param usrFaxNm
     * @param usrPhnNmbr
     * @param returnDesc
     * @param usrMblNmbr
     */
    @WebMethod(operationName = "EditUser")
    @RequestWrapper(localName = "EditUser", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserType")
    @ResponseWrapper(localName = "EditUserResponse", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserResponseType")
    public void editUser(
        @WebParam(name = "UsrNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrNm,
        @WebParam(name = "UnqId", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> unqId,
        @WebParam(name = "RlCrdnts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<List<RoleCoordinatesType>> rlCrdnts,
        @WebParam(name = "UsrTtle", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<UserTitleType> usrTtle,
        @WebParam(name = "UsrFrstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrFrstNm,
        @WebParam(name = "UsrLstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrLstNm,
        @WebParam(name = "UsrPhnNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrPhnNmbr,
        @WebParam(name = "UsrMblNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrMblNmbr,
        @WebParam(name = "UsrEmail", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrEmail,
        @WebParam(name = "UsrFaxNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrFaxNm,
        @WebParam(name = "CmmnNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> cmmnNm,
        @WebParam(name = "UsrPsswrd", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrPsswrd,
        @WebParam(name = "UsrLng", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<LanguageType> usrLng,
        @WebParam(name = "UsrSts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<StatusType> usrSts,
        @WebParam(name = "returnCode", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnCode,
        @WebParam(name = "returnDesc", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnDesc);

    /**
     * 
     * @param returnCode
     * @param usrTtle
     * @param usrSts
     * @param unqId
     * @param usrFrstNm
     * @param usrLng
     * @param usrEmail
     * @param rlCrdnts
     * @param usrLstNm
     * @param cmmnNm
     * @param usrNm
     * @param usrPsswrd
     * @param usrFaxNm
     * @param usrPhnNmbr
     * @param returnDesc
     * @param usrMblNmbr
     */
    @WebMethod(operationName = "ViewUser")
    @RequestWrapper(localName = "ViewUser", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserIdType")
    @ResponseWrapper(localName = "ViewUserResponse", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserResponseType")
    public void viewUser(
        @WebParam(name = "UsrNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrNm,
        @WebParam(name = "UnqId", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> unqId,
        @WebParam(name = "RlCrdnts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<List<RoleCoordinatesType>> rlCrdnts,
        @WebParam(name = "UsrTtle", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<UserTitleType> usrTtle,
        @WebParam(name = "UsrFrstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFrstNm,
        @WebParam(name = "UsrLstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrLstNm,
        @WebParam(name = "UsrPhnNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPhnNmbr,
        @WebParam(name = "UsrMblNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrMblNmbr,
        @WebParam(name = "UsrEmail", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrEmail,
        @WebParam(name = "UsrFaxNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFaxNm,
        @WebParam(name = "CmmnNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> cmmnNm,
        @WebParam(name = "UsrPsswrd", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPsswrd,
        @WebParam(name = "UsrLng", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<LanguageType> usrLng,
        @WebParam(name = "UsrSts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<StatusType> usrSts,
        @WebParam(name = "returnCode", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnCode,
        @WebParam(name = "returnDesc", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnDesc);

    /**
     * 
     * @param returnCode
     * @param usrTtle
     * @param usrSts
     * @param unqId
     * @param usrFrstNm
     * @param usrLng
     * @param usrEmail
     * @param rlCrdnts
     * @param usrLstNm
     * @param cmmnNm
     * @param usrNm
     * @param usrPsswrd
     * @param usrFaxNm
     * @param usrPhnNmbr
     * @param returnDesc
     * @param usrMblNmbr
     */
    @WebMethod(operationName = "ActivateUser")
    @RequestWrapper(localName = "ActivateUser", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserIdType")
    @ResponseWrapper(localName = "ActivateUserResponse", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserResponseType")
    public void activateUser(
        @WebParam(name = "UsrNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrNm,
        @WebParam(name = "UnqId", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> unqId,
        @WebParam(name = "RlCrdnts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<List<RoleCoordinatesType>> rlCrdnts,
        @WebParam(name = "UsrTtle", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<UserTitleType> usrTtle,
        @WebParam(name = "UsrFrstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFrstNm,
        @WebParam(name = "UsrLstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrLstNm,
        @WebParam(name = "UsrPhnNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPhnNmbr,
        @WebParam(name = "UsrMblNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrMblNmbr,
        @WebParam(name = "UsrEmail", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrEmail,
        @WebParam(name = "UsrFaxNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFaxNm,
        @WebParam(name = "CmmnNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> cmmnNm,
        @WebParam(name = "UsrPsswrd", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPsswrd,
        @WebParam(name = "UsrLng", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<LanguageType> usrLng,
        @WebParam(name = "UsrSts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<StatusType> usrSts,
        @WebParam(name = "returnCode", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnCode,
        @WebParam(name = "returnDesc", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnDesc);

    /**
     * 
     * @param returnCode
     * @param usrTtle
     * @param usrSts
     * @param unqId
     * @param usrFrstNm
     * @param usrLng
     * @param usrEmail
     * @param rlCrdnts
     * @param usrLstNm
     * @param cmmnNm
     * @param usrNm
     * @param usrPsswrd
     * @param usrFaxNm
     * @param usrPhnNmbr
     * @param returnDesc
     * @param usrMblNmbr
     */
    @WebMethod(operationName = "DeactivateUser")
    @RequestWrapper(localName = "DeactivateUser", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserIdType")
    @ResponseWrapper(localName = "DeactivateUserResponse", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", className = "com.sentenial.ws.client.usermgmnt.UserResponseType")
    public void deactivateUser(
        @WebParam(name = "UsrNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> usrNm,
        @WebParam(name = "UnqId", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<String> unqId,
        @WebParam(name = "RlCrdnts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.INOUT)
        Holder<List<RoleCoordinatesType>> rlCrdnts,
        @WebParam(name = "UsrTtle", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<UserTitleType> usrTtle,
        @WebParam(name = "UsrFrstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFrstNm,
        @WebParam(name = "UsrLstNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrLstNm,
        @WebParam(name = "UsrPhnNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPhnNmbr,
        @WebParam(name = "UsrMblNmbr", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrMblNmbr,
        @WebParam(name = "UsrEmail", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrEmail,
        @WebParam(name = "UsrFaxNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrFaxNm,
        @WebParam(name = "CmmnNm", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> cmmnNm,
        @WebParam(name = "UsrPsswrd", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> usrPsswrd,
        @WebParam(name = "UsrLng", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<LanguageType> usrLng,
        @WebParam(name = "UsrSts", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<StatusType> usrSts,
        @WebParam(name = "returnCode", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnCode,
        @WebParam(name = "returnDesc", targetNamespace = "urn:com:sentenial:origix:ws:usermgmnt-ws", mode = WebParam.Mode.OUT)
        Holder<String> returnDesc);

}
