
package com.sentenial.ws.client.system;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ping", targetNamespace = "urn:com:sentenial:origix:ws:system:ping:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ping {


    /**
     * 
     * @param pingRequest
     * @return
     *     returns com.sentenial.ws.client.system.PingResponse
     */
    @WebMethod(operationName = "Ping")
    @WebResult(name = "PingResponse", targetNamespace = "urn:com:sentenial:origix:ws:system:ping", partName = "PingResponse")
    public PingResponse ping(
        @WebParam(name = "PingRequest", targetNamespace = "urn:com:sentenial:origix:ws:system:ping", partName = "PingRequest")
        PingRequest pingRequest);

}
