
package com.sentenial.ws.client.system;

import com.sentenial.ws.service.WsSettingsLoader;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "urn:com:sentenial:origix:ws:system:ping:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir4623729307622538314.tmp/ping_1.wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PINGSERVICE_EXCEPTION;
    private final static QName PINGSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:system:ping:wsdl", "PingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = WsSettingsLoader.getClassLoader().getResource("com/sentenial/origix/ws/system/ping.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        PINGSERVICE_WSDL_LOCATION = url;
        PINGSERVICE_EXCEPTION = e;
    }

    public PingService() {
        super(__getWsdlLocation(), PINGSERVICE_QNAME);
    }

    public PingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation) {
        super(wsdlLocation, PINGSERVICE_QNAME);
    }

    public PingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingSoap11")
    public Ping getPingSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:system:ping:wsdl", "PingSoap11"), Ping.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingSoap11")
    public Ping getPingSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:system:ping:wsdl", "PingSoap11"), Ping.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PINGSERVICE_EXCEPTION!= null) {
            throw PINGSERVICE_EXCEPTION;
        }
        return PINGSERVICE_WSDL_LOCATION;
    }

}
