
package com.sentenial.ws.client.ct;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditTransferWs", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditTransferWs {


    /**
     * 
     * @param addBeneficiaryRequest
     * @return
     *     returns com.sentenial.ws.client.ct.AddBeneficiaryResponse
     */
    @WebMethod(operationName = "AddBeneficiary")
    @WebResult(name = "AddBeneficiaryResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "AddBeneficiaryResponse")
    public AddBeneficiaryResponse addBeneficiary(
        @WebParam(name = "AddBeneficiaryRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "AddBeneficiaryRequest")
        AddBeneficiaryRequest addBeneficiaryRequest);

    /**
     * 
     * @param editBeneficiaryRequest
     * @return
     *     returns com.sentenial.ws.client.ct.EditBeneficiaryResponse
     */
    @WebMethod(operationName = "EditBeneficiary")
    @WebResult(name = "EditBeneficiaryResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "EditBeneficiaryResponse")
    public EditBeneficiaryResponse editBeneficiary(
        @WebParam(name = "EditBeneficiaryRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "EditBeneficiaryRequest")
        EditBeneficiaryRequest editBeneficiaryRequest);

    /**
     * 
     * @param viewBeneficiaryRequest
     * @return
     *     returns com.sentenial.ws.client.ct.ViewBeneficiaryResponse
     */
    @WebMethod(operationName = "ViewBeneficiary")
    @WebResult(name = "ViewBeneficiaryResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ViewBeneficiaryResponse")
    public ViewBeneficiaryResponse viewBeneficiary(
        @WebParam(name = "ViewBeneficiaryRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ViewBeneficiaryRequest")
        ViewBeneficiaryRequest viewBeneficiaryRequest);

    /**
     * 
     * @param addCreditTransferRequest
     * @return
     *     returns com.sentenial.ws.client.ct.AddCreditTransferResponse
     */
    @WebMethod(operationName = "AddCreditTransfer")
    @WebResult(name = "AddCreditTransferResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "AddCreditTransferResponse")
    public AddCreditTransferResponse addCreditTransfer(
        @WebParam(name = "AddCreditTransferRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "AddCreditTransferRequest")
        AddCreditTransferRequest addCreditTransferRequest);

    /**
     * 
     * @param viewCreditTransferRequest
     * @return
     *     returns com.sentenial.ws.client.ct.ViewCreditTransferResponse
     */
    @WebMethod(operationName = "ViewCreditTransfer")
    @WebResult(name = "ViewCreditTransferResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ViewCreditTransferResponse")
    public ViewCreditTransferResponse viewCreditTransfer(
        @WebParam(name = "ViewCreditTransferRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ViewCreditTransferRequest")
        ViewCreditTransferRequest viewCreditTransferRequest);

    /**
     * 
     * @param listCreditTransferRequest
     * @return
     *     returns com.sentenial.ws.client.ct.ListCreditTransferResponse
     */
    @WebMethod(operationName = "ListCreditTransfer")
    @WebResult(name = "ListCreditTransferResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ListCreditTransferResponse")
    public ListCreditTransferResponse listCreditTransfer(
        @WebParam(name = "ListCreditTransferRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ListCreditTransferRequest")
        ListCreditTransferRequest listCreditTransferRequest);

    /**
     * 
     * @param recallCreditTransferRequest
     * @return
     *     returns com.sentenial.ws.client.ct.RecallCreditTransferResponse
     */
    @WebMethod(operationName = "RecallCreditTransfer")
    @WebResult(name = "RecallCreditTransferResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "RecallCreditTransferResponse")
    public RecallCreditTransferResponse recallCreditTransfer(
        @WebParam(name = "RecallCreditTransferRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "RecallCreditTransferRequest")
        RecallCreditTransferRequest recallCreditTransferRequest);

    /**
     * 
     * @param listFailedCreditTransferRequest
     * @return
     *     returns com.sentenial.ws.client.ct.ListFailedCreditTransferResponse
     */
    @WebMethod(operationName = "ListFailedCTPayments")
    @WebResult(name = "ListFailedCreditTransferResponse", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ListFailedCreditTransferResponse")
    public ListFailedCreditTransferResponse listFailedCTPayments(
        @WebParam(name = "ListFailedCreditTransferRequest", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws", partName = "ListFailedCreditTransferRequest")
        ListFailedCreditTransferRequest listFailedCreditTransferRequest);

}
