
package com.sentenial.ws.client.ct;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditTransferWsService", targetNamespace = "urn:com:sentenial:origix:ws:credittransfer-ws:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir6941166071607197203.tmp/credittransfer-ws_1.wsdl")
public class CreditTransferWsService
    extends Service
{

    private final static URL CREDITTRANSFERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITTRANSFERWSSERVICE_EXCEPTION;
    private final static QName CREDITTRANSFERWSSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:credittransfer-ws:wsdl", "CreditTransferWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir6941166071607197203.tmp/credittransfer-ws_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITTRANSFERWSSERVICE_WSDL_LOCATION = url;
        CREDITTRANSFERWSSERVICE_EXCEPTION = e;
    }

    public CreditTransferWsService() {
        super(__getWsdlLocation(), CREDITTRANSFERWSSERVICE_QNAME);
    }

    public CreditTransferWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITTRANSFERWSSERVICE_QNAME, features);
    }

    public CreditTransferWsService(URL wsdlLocation) {
        super(wsdlLocation, CREDITTRANSFERWSSERVICE_QNAME);
    }

    public CreditTransferWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITTRANSFERWSSERVICE_QNAME, features);
    }

    public CreditTransferWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditTransferWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditTransferWs
     */
    @WebEndpoint(name = "CreditTransferWsSoap11")
    public CreditTransferWs getCreditTransferWsSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:credittransfer-ws:wsdl", "CreditTransferWsSoap11"), CreditTransferWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditTransferWs
     */
    @WebEndpoint(name = "CreditTransferWsSoap11")
    public CreditTransferWs getCreditTransferWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:credittransfer-ws:wsdl", "CreditTransferWsSoap11"), CreditTransferWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITTRANSFERWSSERVICE_EXCEPTION!= null) {
            throw CREDITTRANSFERWSSERVICE_EXCEPTION;
        }
        return CREDITTRANSFERWSSERVICE_WSDL_LOCATION;
    }

}
