
package com.sentenial.ws.client.accountvalidation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountValidationWs", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountValidationWs {


    /**
     * 
     * @param validateIBANAccountRequest
     * @return
     *     returns com.sentenial.ws.client.accountvalidation.ValidateAccountResponse
     */
    @WebMethod(operationName = "ValidateIBANAccount")
    @WebResult(name = "ValidateAccountResponse", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws", partName = "ValidateAccountResponse")
    public ValidateAccountResponse validateIBANAccount(
        @WebParam(name = "ValidateIBANAccountRequest", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws", partName = "ValidateIBANAccountRequest")
        ValidateIBANAccountRequest validateIBANAccountRequest);

    /**
     * 
     * @param validateDomesticAccountRequest
     * @return
     *     returns com.sentenial.ws.client.accountvalidation.ValidateAccountResponse
     */
    @WebMethod(operationName = "ValidateDomesticAccount")
    @WebResult(name = "ValidateAccountResponse", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws", partName = "ValidateAccountResponse")
    public ValidateAccountResponse validateDomesticAccount(
        @WebParam(name = "ValidateDomesticAccountRequest", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws", partName = "ValidateDomesticAccountRequest")
        ValidateDomesticAccountRequest validateDomesticAccountRequest);

}
