
package com.sentenial.ws.client.accountvalidation;

import com.sentenial.ws.service.WsSettingsLoader;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountValidationWsService", targetNamespace = "urn:com:sentenial:origix:ws:accountvalidation-ws:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir2123850951729047285.tmp/accountvalidation-ws_1.wsdl")
public class AccountValidationWsService
    extends Service
{

    private final static URL ACCOUNTVALIDATIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTVALIDATIONWSSERVICE_EXCEPTION;
    private final static QName ACCOUNTVALIDATIONWSSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:accountvalidation-ws:wsdl", "AccountValidationWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = WsSettingsLoader.getClassLoader().getResource("com/sentenial/origix/ws/accountvalidation/accountvalidation-ws.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTVALIDATIONWSSERVICE_WSDL_LOCATION = url;
        ACCOUNTVALIDATIONWSSERVICE_EXCEPTION = e;
    }

    public AccountValidationWsService() {
        super(__getWsdlLocation(), ACCOUNTVALIDATIONWSSERVICE_QNAME);
    }

    public AccountValidationWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTVALIDATIONWSSERVICE_QNAME, features);
    }

    public AccountValidationWsService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTVALIDATIONWSSERVICE_QNAME);
    }

    public AccountValidationWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTVALIDATIONWSSERVICE_QNAME, features);
    }

    public AccountValidationWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountValidationWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountValidationWs
     */
    @WebEndpoint(name = "AccountValidationWsSoap11")
    public AccountValidationWs getAccountValidationWsSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:accountvalidation-ws:wsdl", "AccountValidationWsSoap11"), AccountValidationWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountValidationWs
     */
    @WebEndpoint(name = "AccountValidationWsSoap11")
    public AccountValidationWs getAccountValidationWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:accountvalidation-ws:wsdl", "AccountValidationWsSoap11"), AccountValidationWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTVALIDATIONWSSERVICE_EXCEPTION!= null) {
            throw ACCOUNTVALIDATIONWSSERVICE_EXCEPTION;
        }
        return ACCOUNTVALIDATIONWSSERVICE_WSDL_LOCATION;
    }

}
