
package com.sentenial.ws.client.accountvalidation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentScheduleWs", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentScheduleWs {


    /**
     * 
     * @param addPaymentScheduleRequest
     * @return
     *     returns com.sentenial.ws.client.accountvalidation.AddPaymentScheduleResponse
     */
    @WebMethod(operationName = "AddPaymentSchedule")
    @WebResult(name = "AddPaymentScheduleResponse", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws", partName = "AddPaymentScheduleResponse")
    public AddPaymentScheduleResponse addPaymentSchedule(
        @WebParam(name = "AddPaymentScheduleRequest", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws", partName = "AddPaymentScheduleRequest")
        AddPaymentScheduleRequest addPaymentScheduleRequest);

    /**
     * 
     * @param editPaymentScheduleRequest
     * @return
     *     returns com.sentenial.ws.client.accountvalidation.EditPaymentScheduleResponse
     */
    @WebMethod(operationName = "EditPaymentSchedule")
    @WebResult(name = "EditPaymentScheduleResponse", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws", partName = "EditPaymentScheduleResponse")
    public EditPaymentScheduleResponse editPaymentSchedule(
        @WebParam(name = "EditPaymentScheduleRequest", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws", partName = "EditPaymentScheduleRequest")
        EditPaymentScheduleRequest editPaymentScheduleRequest);

}
