
package com.sentenial.ws.client.accountvalidation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentScheduleWsService", targetNamespace = "urn:com:sentenial:origix:ws:paymentschedule-ws:wsdl", wsdlLocation = "file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir4978644122389340549.tmp/paymentschedule-ws_1.wsdl")
public class PaymentScheduleWsService
    extends Service
{

    private final static URL PAYMENTSCHEDULEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSCHEDULEWSSERVICE_EXCEPTION;
    private final static QName PAYMENTSCHEDULEWSSERVICE_QNAME = new QName("urn:com:sentenial:origix:ws:paymentschedule-ws:wsdl", "PaymentScheduleWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/christian.reichel/AppData/Local/Temp/tempdir4978644122389340549.tmp/paymentschedule-ws_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSCHEDULEWSSERVICE_WSDL_LOCATION = url;
        PAYMENTSCHEDULEWSSERVICE_EXCEPTION = e;
    }

    public PaymentScheduleWsService() {
        super(__getWsdlLocation(), PAYMENTSCHEDULEWSSERVICE_QNAME);
    }

    public PaymentScheduleWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSCHEDULEWSSERVICE_QNAME, features);
    }

    public PaymentScheduleWsService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSCHEDULEWSSERVICE_QNAME);
    }

    public PaymentScheduleWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSCHEDULEWSSERVICE_QNAME, features);
    }

    public PaymentScheduleWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentScheduleWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentScheduleWs
     */
    @WebEndpoint(name = "PaymentScheduleWsSoap11")
    public PaymentScheduleWs getPaymentScheduleWsSoap11() {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:paymentschedule-ws:wsdl", "PaymentScheduleWsSoap11"), PaymentScheduleWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentScheduleWs
     */
    @WebEndpoint(name = "PaymentScheduleWsSoap11")
    public PaymentScheduleWs getPaymentScheduleWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:com:sentenial:origix:ws:paymentschedule-ws:wsdl", "PaymentScheduleWsSoap11"), PaymentScheduleWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSCHEDULEWSSERVICE_EXCEPTION!= null) {
            throw PAYMENTSCHEDULEWSSERVICE_EXCEPTION;
        }
        return PAYMENTSCHEDULEWSSERVICE_WSDL_LOCATION;
    }

}
